name: Build Holo Docker images

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Login to GitHub Container Registry
      run: |
        echo $GITHUB_TOKEN | docker login ghcr.io -u valerie-tar-gz --password-stdin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Download SteamOS
      id: download
      run: ./download.sh >>$GITHUB_OUTPUT

    - name: Build and tag base image
      run: |
        sudo ./build.sh

    - name: Cleanup SteamOS image
      run: rm -rf ./steamos_image ./steamos

    - name: Tag all images
      run: |
        for tag in \
            "${{ steps.download.outputs.BUILD_ID }}" \
            "${{ steps.download.outputs.FULL_VERSION }}" \
            "${{ steps.download.outputs.MAJOR_VERSION }}" \
            "${{ steps.download.outputs.MINOR_VERSION }}"
        do
          docker tag ghcr.io/valerie-tar-gz/holo-docker-complete:latest             ghcr.io/valerie-tar-gz/holo-docker-complete:$tag
          docker tag ghcr.io/valerie-tar-gz/holo-docker-minimal:latest             ghcr.io/valerie-tar-gz/holo-docker-minimal:$tag
        done

    - name: Wait for other runs to complete
      uses: softprops/turnstyle@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Base image
      run: docker push --all-tags ghcr.io/valerie-tar-gz/holo-docker-complete

    - name: Push Minimal image
      run: docker push --all-tags ghcr.io/valerie-tar-gz/holo-docker-minimal

    - name: Log out of GitHub Container Registry
      run: |
        docker logout ghcr.io
